export const iAmWords = [
    'Designer', 
    'Producer', 
    'Creative writer', 
    'Visual thinker', 
    'Communicator', 
    'Solution seeker', 
    'Budget manager', 
    'Logistics coordinator', 
    'Art director', 
    'Stylist', 
    'Conceptual creator', 
    'Sustainability advocate', 
    'Fashion storyteller', 
    'Experience curator', 
    'Deep listener', 
    'Nature lover', 
    'Collaborator', 
    'Innovator', 
    'Advocate for social change', 
    'Storyteller through design', 
    'Researcher'
]

export const interestsWords = [
    'Poetry',
    'Sustainability',
    'Field recording',
    'Traveling',
    'Swimming',
    'Gardening with intention',
    'Nature in all its forms',
    'Observing the rhythm of the seasons',
    'Noble materials',
    'Regenerative design',
    'Collective storytelling',
    'Fashion with meaning',
    'Silence as a language',
    'Workshops as meeting spaces',
    'Cultivating community',
    'What is not always seen',
    'Listening beyond what is said',
    'Care as a form of creation',
    'The handmade and the digital',
    'Crossing disciplines',
    'Imagining possible futures',
    'Creating from emotion',
    'The power of the invisible',
    'Learning from the earth'
]
